# Generated by Django 5.0.3 on 2024-03-17 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('main_photo', models.FileField(upload_to='news/photos/')),
                ('text', models.TextField()),
                ('video', models.FileField(default=None, null=True, upload_to='news/videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalPhotosOfNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='news/additional-photos/')),
                ('fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additionalPhotos', to='news.news')),
            ],
        ),
    ]
