# Generated by Django 5.0.3 on 2024-03-16 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutdoc', '0002_document_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('file', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
