# Generated by Django 5.0.3 on 2024-03-16 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutdoc', '0003_catalog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Catalog',
        ),
    ]
