# Generated by Django 5.0.3 on 2024-03-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_poiskpravoobladateley'),
    ]

    operations = [
        migrations.CreateModel(
            name='InostrannyeOkupy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('title', models.CharField(max_length=255)),
            ],
        ),
    ]
