# Generated by Django 5.0.3 on 2024-03-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_inostrannyeokupy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poiskpravoobladateley',
            name='file',
            field=models.FileField(upload_to='PoiskPravoobladateley/'),
        ),
        migrations.AlterField(
            model_name='reestr',
            name='file',
            field=models.FileField(upload_to='reestrs/'),
        ),
    ]
